### ISSUE TITLE
Rename repository?

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/python-simplegeneric-feedstock#7]
Should this repository be renamed to reflect the change in the name of the package from `python-simplegeneric` to `simplegeneric`?  See #3.

**Comment by ocefpaf** [comment]
This feedstock will be removed and re-added with the `pathlib2` name once https://github.com/conda-forge/staged-recipes/pull/3554 is merged.

Ping @conda-forge/python-simplegeneric

**Comment by ocefpaf** [comment]
Removing this feedstock now that https://github.com/conda-forge/staged-recipes/pull/3554 got merged.
